# 1. Build Stage
FROM node:18-alpine

WORKDIR /app

# Copy dependency definitions
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .

# Expose the port Vite runs on
EXPOSE 5173

# Start the dev server
CMD ["npm", "run", "dev", "--", "--host"]